TRUNCATE individual_client RESTART IDENTITY CASCADE;
TRUNCATE entity_client RESTART IDENTITY CASCADE;
TRUNCATE account RESTART IDENTITY CASCADE;
TRUNCATE service RESTART IDENTITY CASCADE;
TRUNCATE operation RESTART IDENTITY CASCADE;
TRUNCATE connected_service RESTART IDENTITY CASCADE;
