DROP TYPE IF EXISTS ACCOUNT_STATUS;
DROP TYPE IF EXISTS OPERATION_TYPE;
DROP TYPE IF EXISTS SUBSCRIPTION_TYPE;

DROP TABLE IF EXISTS individual_client;
DROP TABLE IF EXISTS entity_client;
DROP TABLE IF EXISTS account;
DROP TABLE IF EXISTS operation;
DROP TABLE IF EXISTS service;
DROP TABLE IF EXISTS connected_service;