DROP TYPE IF EXISTS ACCOUNT_STATUS CASCADE;
DROP TYPE IF EXISTS OPERATION_TYPE CASCADE;
DROP TYPE IF EXISTS SUBSCRIPTION_TYPE CASCADE;

DROP TABLE IF EXISTS individual_client CASCADE;
DROP TABLE IF EXISTS entity_client CASCADE;
DROP TABLE IF EXISTS account CASCADE;
DROP TABLE IF EXISTS operation CASCADE;
DROP TABLE IF EXISTS service CASCADE;
DROP TABLE IF EXISTS connected_service CASCADE;

DROP TRIGGER IF EXISTS account_manipulation ON account CASCADE;
DROP TRIGGER IF EXISTS account_manipulation_balance ON account CASCADE;
DROP TRIGGER IF EXISTS account_manipulation_status ON account CASCADE;
DROP TRIGGER IF EXISTS service_connection ON connected_service CASCADE;

DROP FUNCTION IF EXISTS check_account_status CASCADE;
DROP FUNCTION IF EXISTS log_account_balance CASCADE;
DROP FUNCTION IF EXISTS log_account_status CASCADE;
DROP FUNCTION IF EXISTS log_service_connection CASCADE;